version: '3.8'

services:
  mlbenchmark:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  # Frontend dev server
      - "8000:8000"  # Backend API
      - "80:80"      # Nginx
    volumes:
      - ./frontend:/app/frontend
      - ./backend:/app/backend
      - /app/frontend/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8000
      - HOST=0.0.0.0
      - PORT=8000
      - WATCHFILES_FORCE_POLLING=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

  # Optional Redis cache (if needed)
  # cache:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   command: redis-server --appendonly yes
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3

volumes:
  redis_data:

networks:
  default:
    name: mlbenchmark-network
    driver: bridge
